// File: lib/firebase_options.dart
// Generated by: flutterfire configure (or manually)
// This file is safe to commit ONLY if you have restricted the API key in Google Cloud

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// After you regenerate a new safe API key, just replace the apiKey below.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ╔══════════════════════════════════════════════════════════
  // │ PUT YOUR NEW (SAFE) API KEY HERE AFTER YOU REGENERATE │
  // ╚══════════════════════════════════════════════════════════
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyB-5nmrGZw-S94DZdmmNFxuu6xCBDP9i-c",
    authDomain: "student-register-smosnea.firebaseapp.com",
    projectId: "student-register-smosnea",
    storageBucket: "student-register-smosnea.firebasestorage.app",
    messagingSenderId: "906522554188",
    appId: "1:906522554188:web:81efda0233b80bf9d5a9e9",
    measurementId: "G-PHVC14BG3X",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyB-5nmrGZw-S94DZdmmNFxuu6xCBDP9i-c",
    authDomain: "student-register-smosnea.firebaseapp.com",
    projectId: "student-register-smosnea",
    storageBucket: "student-register-smosnea.firebasestorage.app",
    messagingSenderId: "906522554188",
    appId: "1:906522554188:web:81efda0233b80bf9d5a9e9",
    measurementId: "G-PHVC14BG3X",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyB-5nmrGZw-S94DZdmmNFxuu6xCBDP9i-c",
    authDomain: "student-register-smosnea.firebaseapp.com",
    projectId: "student-register-smosnea",
    storageBucket: "student-register-smosnea.firebasestorage.app",
    messagingSenderId: "906522554188",
    appId: "1:906522554188:web:81efda0233b80bf9d5a9e9",
    measurementId: "G-PHVC14BG3X",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyB-5nmrGZw-S94DZdmmNFxuu6xCBDP9i-c",
    authDomain: "student-register-smosnea.firebaseapp.com",
    projectId: "student-register-smosnea",
    storageBucket: "student-register-smosnea.firebasestorage.app",
    messagingSenderId: "906522554188",
    appId: "1:906522554188:web:81efda0233b80bf9d5a9e9",
    measurementId: "G-PHVC14BG3X",
  );
}
